joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

j2_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints: 
      - J2Rotation
